#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Exactly 1 argument is required"
    exit
fi

SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [ -f "$SCRIPT_FILE" ]; then
  gvim "$SCRIPT_FILE" &
else

cat >> "$SCRIPT_FILE" <<EOF
#!/bin/sh

# vim: expandtab sw=2 ts=2
EOF

  chmod +x "$SCRIPT_FILE"
  gvim "$SCRIPT_FILE" &
fi

# vim: expandtab sw=2 ts=2
