#!/usr/bin/bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -p "Service" "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	if pass show -c "$password" 2>&1 | grep "is not in the password store"; then
        length=$(rofi -dmenu -p "Length" "$@")
        pass generate -c "$password" "$length"
    fi
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
fi
